# Heavily inspired by: https://github.com/bevyengine/bevy/tree/main/examples/mobile

[versions]
agp = "8.13.2"
appcompat = "1.7.1"
core = "1.17.0"
# FIXME: This is now 4.0.0, but android-activity 0.6.0 is only compatible with major version 2.
#        Also see:
#        - https://github.com/rust-mobile/android-activity/discussions/208
#        - https://github.com/rust-mobile/android-activity/issues/210
gamesActivity = "2.0.2"
material = "1.13.0"

[libraries]
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
core = { group = "androidx.core", name = "core", version.ref = "core" }
games-activity = { group = "androidx.games", name = "games-activity", version.ref = "gamesActivity" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
