# Heavily inspired by:
# - https://github.com/bevyengine/bevy_github_ci_template
# - https://github.com/TheBevyFlock/bevy_new_2d

name: Android Testing (Debug)

on:
  push:
    branches: [android-testing]

# Cancel the release workflow when a more recent workflow begins.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

# Configure the release workflow by editing the following values.
env:
  # Which platforms to build for or deploy to
  build_for_android: true
  build_for_linux-x86_64: false
  build_for_linux-aarch64: false
  build_for_macos: false
  build_for_web: false
  build_for_windows: false
  deploy_to_github_pages: false
  deploy_to_itch: false
  upload_to_github: false

  # Deny rust warnings
  deny_warnings: false

  # The base filename of the binary produced by `cargo build`.
  cargo_build_binary_name: bevy-slime-dodge

  # The path to the assets directory.
  assets_path: assets

  # The path to the libraries directory.
  libs_path: lib

  # The itch.io project to deploy to in the format `user-name/project-name`.
  # There will be no deployment to itch.io if this is commented out.
  #itch_page: the-bevy-flock/bevy-new-2d

  # The ID of the app produced by this workflow.
  # Applies to macOS releases.
  # Must contain only A-Z, a-z, 0-9, hyphen, and period: <https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundleidentifier>.
  app_id: dev.meinel.leo.bevy-slime-dodge

  # The base filename of the binary in the package produced by this workflow.
  # Applies to Windows, macOS, and Linux releases.
  # Defaults to `cargo_build_binary_name` if commented out.
  #app_binary_name: bevy_new_2d

  # The name of the `.zip` or `.dmg` file produced by this workflow.
  # Defaults to `app_binary_name` if commented out.
  #app_package_name: bevy-new-2d

  # The display name of the app produced by this workflow.
  # Applies to macOS releases.
  # Defaults to `app_package_name` if commented out.
  #app_display_name: Bevy New 2D

  # The short display name of the app produced by this workflow.
  # Applies to macOS releases.
  # Must be 15 or fewer characters: <https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundlename>.
  # Defaults to `app_display_name` if commented out.
  #app_short_name: Bevy New 2D

  # Before enabling LFS, please take a look at GitHub's documentation for costs and quota limits:
  # <https://docs.github.com/en/repositories/working-with-files/managing-large-files/about-storage-and-bandwidth-usage>
  git_lfs: false

  # Enabling this only helps with consecutive releases to the same version (and takes up cache storage space).
  # See: <https://github.com/orgs/community/discussions/27059>.
  use_github_cache: false

jobs:
  # Forward some environment variables as outputs of this job.
  # This is needed because the `env` context can't be used in the `if:` condition of a job:
  # <https://docs.github.com/en/actions/learn-github-actions/contexts#context-availability>
  forward-env:
    runs-on: ubuntu-latest
    steps:
      - name: Do nothing
        run: "true"
    outputs:
      build_for_web: ${{ env.build_for_web }}
      deploy_to_github_pages: ${{ env.deploy_to_github_pages }}
      deploy_to_itch: ${{ env.deploy_to_itch }}
      itch_page: ${{ env.itch_page }}
      upload_to_github: ${{ env.upload_to_github }}

  # Determine the version number for this workflow.
  get-version:
    runs-on: ubuntu-latest
    steps:
      - name: Determine version number
        id: tag
        run: |
          ref=${{ github.ref }}
          ref=${ref#refs/*/}
          ref=${ref#v}
          printf "%s\n" "ref=$ref" >> ${GITHUB_OUTPUT}
    outputs:
      # Use the input from workflow dispatch, or fall back to the git ref.
      version: ${{ steps.tag.outputs.ref }}

  # Build and package a release for each platform.
  build:
    needs:
      - get-version
    env:
      version: ${{ needs.get-version.outputs.version }}
      # Avoid rate-limiting. See: <https://github.com/cargo-bins/cargo-binstall/issues/2045>.
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      matrix:
        include:
          - platform: web
            targets: wasm32-unknown-unknown
            binary_ext: .wasm
            package_ext: .zip
            runner: ubuntu-latest

          # FIXME: Add app signing
          - platform: android
            # FIXME: Readd missing targets: armv7-linux-androideabi x86_64-linux-android
            targets: aarch64-linux-android
            package_ext: .zip
            runner: ubuntu-latest

          - platform: linux-x86_64
            targets: x86_64-unknown-linux-gnu
            package_ext: .zip
            runner: ubuntu-latest

          - platform: linux-aarch64
            targets: aarch64-unknown-linux-gnu
            package_ext: .zip
            runner: ubuntu-24.04-arm

          - platform: windows
            targets: x86_64-pc-windows-msvc
            binary_ext: .exe
            package_ext: .zip
            runner: windows-latest

          - platform: macos
            targets: x86_64-apple-darwin aarch64-apple-darwin
            app_suffix: .app/Contents/MacOS
            package_ext: .dmg
            runner: macos-latest

          # FIXME: Implement this
          - platform: ios
            targets: aarch64-apple-ios x86_64-apple-ios aarch64-apple-ios-sim
            runner: macos-latest
    runs-on: ${{ matrix.runner }}
    permissions:
      # Required to create a GitHub release: <https://docs.github.com/en/rest/releases/releases#create-a-release>.
      contents: write
    defaults:
      run:
        shell: bash

    steps:
      - name: Set up environment
        run: |
          # Default values:
          printf "%s\n" "app_binary_name=${app_binary_name:=${{ env.cargo_build_binary_name }}}" >> "${GITHUB_ENV}"
          printf "%s\n" "app_package_name=${app_package_name:=${app_binary_name}}" >> "${GITHUB_ENV}"
          printf "%s\n" "app_display_name=${app_display_name:=${app_package_name}}" >> "${GITHUB_ENV}"
          printf "%s\n" "app_short_name=${app_short_name:=${app_display_name}}" >> "${GITHUB_ENV}"

          # File paths:
          printf "%s\n" "app=tmp/app/${app_package_name}"'${{ matrix.app_suffix }}' >> "${GITHUB_ENV}"
          printf "%s\n" "package=${app_package_name}-"'${{ matrix.platform }}${{ matrix.package_ext }}' >> "${GITHUB_ENV}"

          # Rustflags:
          # Set up platform library rpaths
          if [ '${{ matrix.platform }}' = 'linux-x86_64' ] || [ '${{ matrix.platform }}' = 'linux-aarch64' ]; then
            RUSTFLAGS="${RUSTFLAGS:+$RUSTFLAGS }"'-C link-arg=-Wl,-rpath,$ORIGIN'
          fi
          if [ '${{ matrix.platform }}' = 'macos' ]; then
            RUSTFLAGS="${RUSTFLAGS:+$RUSTFLAGS }"'-C link-arg=-Wl,-rpath,@loader_path'
          fi

          if [ '${{ env.deny_warnings }}' = 'true' ]; then
            RUSTFLAGS="${RUSTFLAGS:+$RUSTFLAGS }"'-Dwarnings'
          fi
          printf "%s\n" "RUSTFLAGS=${RUSTFLAGS}" >> "${GITHUB_ENV}"

          # macOS environment:
          if [ '${{ matrix.platform }}' = 'macos' ]; then
            printf "%s\n" 'MACOSX_DEPLOYMENT_TARGET=11.0' >> "${GITHUB_ENV}" # macOS 11.0 Big Sur is the first version to support universal binaries.
            printf "%s\n" "SDKROOT=$(xcrun --sdk macosx --show-sdk-path)" >> "${GITHUB_ENV}"
          fi

          # Check if building for this platform is enabled.
          printf "%s\n" 'is_platform_enabled=${{
            (matrix.platform == 'android' && env.build_for_android) ||
            (matrix.platform == 'web' && env.build_for_web) ||
            (matrix.platform == 'linux-x86_64' && env.build_for_linux-x86_64) ||
            (matrix.platform == 'linux-aarch64' && env.build_for_linux-aarch64) ||
            (matrix.platform == 'windows' && env.build_for_windows) ||
            (matrix.platform == 'macos' && env.build_for_macos)
          }}' >> "${GITHUB_ENV}"

      - name: Checkout repository
        if: ${{ env.is_platform_enabled == 'true' }}
        uses: actions/checkout@v4
        with:
          lfs: ${{ env.git_lfs }}

      - name: Install Rust toolchain
        if: ${{ env.is_platform_enabled == 'true' }}
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.targets }}

      - name: Restore Rust cache
        if: ${{ env.is_platform_enabled == 'true' && env.use_github_cache == 'true' }}
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: release
          save-if: ${{ github.ref == 'refs/heads/main' }}

      - name: Install build dependencies (linux-x86_64/linux-aarch64)
        if: ${{ env.is_platform_enabled == 'true' && (matrix.platform == 'linux-x86_64' || matrix.platform == 'linux-aarch64') }}
        run: sudo apt-get update; sudo apt-get install --no-install-recommends libasound2-dev libudev-dev libwayland-dev libxkbcommon-dev

      - name: Prepare output directories
        if: ${{ env.is_platform_enabled == 'true' }}
        run: rm -rf tmp; mkdir -p tmp/binary '${{ env.app }}'

      - name: Install cargo-binstall
        if: ${{ env.is_platform_enabled == 'true' }}
        uses: cargo-bins/cargo-binstall@main

      - name: Set up JDK (Android)
        if: ${{ env.is_platform_enabled == 'true' && matrix.platform == 'android' }}
        uses: actions/setup-java@v5
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "gradle"

      - name: Build and add binaries to app (Android)
        if: ${{ env.is_platform_enabled == 'true' && matrix.platform == 'android' }}
        run: |
          # Install cargo-ndk
          cargo binstall --locked --no-confirm --force cargo-ndk

          # Build package
          for target in ${{ matrix.targets }}; do
            cargo ndk build --no-default-features --release --locked --target="${target}" -o ./mobile/android/app/src/main/jniLibs -j default --link-libcxx-shared
          done
          ## Build apk and sign with signing key
          printf '%s' '${{ secrets.PROD_SIGN_KEYSTORE_BASE64 }}' | openssl base64 -A -d >./mobile/android/app/prod.keystore
          export PROD_KEYSTORE_PASS='${{ secrets.PROD_SIGN_KEYSTORE_PASS }}'
          export PROD_KEY_ALIAS='${{ secrets.PROD_SIGN_KEY_ALIAS }}'
          ./mobile/android/gradlew -p ./mobile/android/ app:assembleRelease
          ## Build aab and sign with upload key
          printf '%s' '${{ secrets.PROD_UPLOAD_KEYSTORE_BASE64 }}' | openssl base64 -A -d >./mobile/android/app/prod.keystore
          export PROD_KEYSTORE_PASS='${{ secrets.PROD_UPLOAD_KEYSTORE_PASS }}'
          export PROD_KEY_ALIAS='${{ secrets.PROD_UPLOAD_KEY_ALIAS }}'
          ./mobile/android/gradlew -p ./mobile/android/ app:bundleRelease

          # Prepare package
          BUILD_OUTPUT=./mobile/android/app/build/outputs
          APK_OUTPUT="${BUILD_OUTPUT}"/apk/release/app-release.apk
          BUNDLE_OUTPUT="${BUILD_OUTPUT}"/bundle/release/app-release.aab
          mv "${APK_OUTPUT}" '${{ env.app }}/${{ env.app_binary_name }}.apk'
          mv "${BUNDLE_OUTPUT}" '${{ env.app }}/${{ env.app_binary_name }}.aab'

      - name: Build and add web bundle to app (Web)
        if: ${{ env.is_platform_enabled == 'true' && matrix.platform == 'web' }}
        run: |
          # Build package
          cargo build --no-default-features --profile web-release --locked --target=${{ matrix.targets }} --features='${{ matrix.features }}' -j default

          # Install binaryen version 125
          curl -LJO https://github.com/WebAssembly/binaryen/releases/download/version_125/binaryen-version_125-x86_64-linux.tar.gz
          tar -xzf ./binaryen-version_125-x86_64-linux.tar.gz

          # Optimize binary
          OUTPUT=target/${{ matrix.targets }}/web-release/${{ env.app_binary_name }}${{ matrix.binary_ext }}
          tmpfile="$(mktemp /tmp/${{ env.app_binary_name }}-XXXXXX${{ matrix.binary_ext }})"
          mv "${OUTPUT}" "${tmpfile}"
          ./binaryen-version_125/bin/wasm-opt -Os -o "${OUTPUT}" "${tmpfile}" --enable-bulk-memory-opt --enable-nontrapping-float-to-int

          cargo binstall --locked --no-confirm --force wasm-bindgen-cli
          wasm-bindgen --no-typescript --out-name bevy_game --out-dir ./web --target web "${OUTPUT}"
          mv ./web/* '${{ env.app }}'

      - name: Build and add binaries to app (non-Android/non-Web/non-Ios)
        if: ${{ env.is_platform_enabled == 'true' && matrix.platform != 'android' && matrix.platform != 'web' && matrix.platform != 'ios' }}
        run: |
          for target in ${{ matrix.targets }}; do
            cargo build --no-default-features --release --locked --target="${target}" --features='${{ matrix.features }}' -j default
            mv target/"${target}"/release/'${{ env.app_binary_name }}${{ matrix.binary_ext }}' tmp/binary/"${target}"'${{ matrix.binary_ext }}'
          done
          if [ '${{ matrix.platform }}' = 'macos' ]; then
            lipo tmp/binary/*'${{ matrix.binary_ext }}' -create -output '${{ env.app }}/${{ env.app_binary_name }}${{ matrix.binary_ext }}'
          else
            mv tmp/binary/*'${{ matrix.binary_ext }}' '${{ env.app }}/${{ env.app_binary_name }}${{ matrix.binary_ext }}'
          fi

      - name: Add assets to app (non-Android/non-Ios)
        if: ${{ env.is_platform_enabled == 'true' && matrix.platform != 'android' && matrix.platform != 'ios' }}
        run: cp -R ./'${{ env.assets_path }}' '${{ env.app }}' || true # Ignore error if assets folder does not exist.

      - name: Add platform libraries (non-Android/non-Web/non-Ios)
        if: ${{ env.is_platform_enabled == 'true' && matrix.platform != 'android' && matrix.platform != 'web' && matrix.platform != 'ios' }}
        run: cp -R ./'${{ env.libs_path }}'/'${{ matrix.platform }}'/* '${{ env.app }}' || true

      - name: Add metadata to app (macOS)
        if: ${{ env.is_platform_enabled == 'true' && matrix.platform == 'macos' }}
        run: |
          cat >'${{ env.app }}/../Info.plist' <<EOF
            <?xml version="1.0" encoding="UTF-8"?>
            <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
            <plist version="1.0">
                <dict>
                    <key>CFBundleDevelopmentRegion</key>
                    <string>en</string>
                    <key>CFBundleDisplayName</key>
                    <string>${{ env.app_display_name }}</string>
                    <key>CFBundleExecutable</key>
                    <string>${{ env.app_binary_name }}</string>
                    <key>CFBundleIdentifier</key>
                    <string>${{ env.app_id }}</string>
                    <key>CFBundleName</key>
                    <string>${{ env.app_short_name }}</string>
                    <key>CFBundleShortVersionString</key>
                    <string>${{ env.version }}</string>
                    <key>CFBundleVersion</key>
                    <string>${{ env.version }}</string>
                    <key>CFBundleInfoDictionaryVersion</key>
                    <string>6.0</string>
                    <key>CFBundlePackageType</key>
                    <string>APPL</string>
                    <key>CFBundleSupportedPlatforms</key>
                    <array>
                        <string>MacOSX</string>
                    </array>
                </dict>
            </plist>
          EOF

      - name: Package app (non-Windows)
        if: ${{ env.is_platform_enabled == 'true' && matrix.platform != 'windows' }}
        working-directory: tmp/app
        run: |
          if [ '${{ matrix.platform }}' = 'macos' ]; then
            ln -s /Applications .
            hdiutil create -fs HFS+ -volname '${{ env.app_package_name }}' -srcfolder . '${{ env.package }}'
          else
            zip --recurse-paths '${{ env.package }}' '${{ env.app_package_name }}'
          fi

      - name: Package app (Windows)
        if: ${{ env.is_platform_enabled == 'true' && matrix.platform == 'windows' }}
        working-directory: tmp/app
        shell: pwsh
        run: Compress-Archive -Path '${{ env.app_package_name }}' -DestinationPath '${{ env.package }}'

      - name: Upload package to workflow artifacts
        if: ${{ env.is_platform_enabled == 'true' }}
        uses: actions/upload-artifact@v4
        with:
          path: tmp/app/${{ env.package }}
          name: package-${{ matrix.platform }}
          retention-days: 1

      - name: Upload web bundle to workflow artifacts for GitHub Pages (Web)
        if: ${{ env.is_platform_enabled == 'true' && matrix.platform == 'web' && needs.forward-env.outputs.deploy_to_github_pages }}
        uses: actions/upload-pages-artifact@v4
        with:
          path: ${{ env.app }}/
          retention-days: 1

      - name: Upload package to GitHub release
        if: ${{ env.is_platform_enabled == 'true' && needs.forward-env.outputs.upload_to_github }}
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: tmp/app/${{ env.package }}
          asset_name: ${{ env.package }}
          release_name: ${{ env.version }}
          tag: ${{ github.ref }}
          overwrite: true

  # Deploy to itch.io.
  deploy-to-itch:
    runs-on: ubuntu-latest
    needs:
      - forward-env
      - get-version
      - build
    if: ${{ needs.forward-env.outputs.deploy_to_itch && needs.forward-env.outputs.itch_page != '' }}

    steps:
      - name: Download packages
        uses: actions/download-artifact@v4
        with:
          pattern: package-*
          path: tmp

      - name: Install butler
        run: |
          curl -L -o butler.zip 'https://broth.itch.zone/butler/linux-amd64/LATEST/archive/default'
          unzip butler.zip
          chmod +x butler
          ./butler -V

      - name: Upload packages to itch.io
        env:
          BUTLER_API_KEY: ${{ secrets.BUTLER_CREDENTIALS }}
        run: |
          for package in $(ls tmp); do
            ./butler push \
              --fix-permissions \
              --userversion='${{ needs.get-version.outputs.version }}' \
              tmp/"${package}"/* \
              '${{ env.itch_page }}':"${package#package-}"
          done

  # Deploy to GitHub Pages.
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    needs:
      - forward-env
      - build
    permissions:
      # Required to deploy to GitHub Pages.
      pages: write
      # Required for GitHub Pages to verify the source of the deployment.
      # See: <https://github.com/actions/deploy-pages/issues/329>.
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    if: ${{ needs.forward-env.outputs.deploy_to_github_pages && needs.forward-env.outputs.build_for_web }}

    steps:
      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4
